#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorR1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR2,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorL1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBlPickup, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBm,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorLft1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLft2,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

  string actS = "score"; //Starting place
  string act1 = "tubes"; //First action
  string act2 = "dropMed"; //Second action

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

/*
*
* HELPER TASKS
*
*/

//Travel set rotations
void forward(int dist, int power)
{
	nMotorEncoder[motorR2] = 0;
	nMotorEncoder[motorL2] = 0;

	while (abs(nMotorEncoder[motorR2]) <= abs(dist))
	{
		if (abs(nMotorEncoder[motorR2]) > abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power;
			motor[motorL1] = power - 10;
			motor[motorR2] = power;
			motor[motorL2] = power - 10;
			PlayTone(300, 3);
		}
		else if (abs(nMotorEncoder[motorR2]) < abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power - 10;
			motor[motorL1] = power;
			motor[motorR2] = power - 10;
			motor[motorL2] = power;
			PlayTone(800, 3);
		}
		else
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
	}
}

//Turn set rotations - 1800 = 45 degrees
void turn(int dist, int powerL, int powerR)
{
	if (powerL < powerR)
	{
		nMotorEncoder[motorL2] = 0;

		while (abs(nMotorEncoder[motorL2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
	else
	{
		nMotorEncoder[motorR2] = 0;

		while (abs(nMotorEncoder[motorR2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
}

//Travel set rotations
void stopMotors()
{
	motor[motorR1] = 0;
	motor[motorL1] = 0;
	motor[motorR2] = 0;
	motor[motorL2] = 0;
}

/*
*
* Core Code
*
*/

//Travel from the scoring zone to the tubes
void lowerToTubes()
{
  forward(2100, -70);
  turn(1400, 10, -60);
  forward(2000, -50);
  turn(1500, -60, 10);
  forward(3600, -40);
}

//Score in medium tube
void dumpMed()
{
	bool runLift = true;

	while(runLift == true)
	{
		motor[motorLft2] = 50;
	 	motor[motorLft1] = 50;
		if(nMotorEncoder[motorLft2] < -2500)
		{
			runLift = false;
		}
	}
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
	while(nMotorEncoder[motorBm] > -650)
	{
		motor[motorBm] = -30;
	}
	while(nMotorEncoder[motorBm] > -1000)
	{
		motor[motorBm] = -1;
	}
	motor[motorBm] = 10;
	Sleep(700);
	motor[motorBm] = 0;

	Sleep(1000);

	int LiftRunning = 1;

	while(nMotorEncoder[motorBm] < -650)
	{
		motor[motorBm] = 30;
	}
	while(nMotorEncoder[motorBm] < -300)
	{
		motor[motorBm] = 1;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(nMotorEncoder[motorBm] < -25)
	{
		motor[motorBm] = 7;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(LiftRunning == 1)
	{
		if(nMotorEncoder[motorLft2] > -720)
		{
			if(nMotorEncoder[motorLft2] < -200)
			{
				motor[motorLft2] = -20;
				motor[motorLft1] = -20;
			}
			else
			{
				motor[motorLft2] = 0;
				motor[motorLft1] = 0;
				LiftRunning = 0;
			}
		}
		else
		{
			motor[motorLft2] = -40;
			motor[motorLft1] = -40;
		}
	}
}

void tubeMed()
{
  turn(1550, 50, -50);
  forward(1300, -50);
	dumpMed();
}

void lowerIR()
{
	//TODO: Get IR position

	//Position 1
	forward(2100, -65);
  turn(1550, -50, 50);
  forward(1000, -35);
  turn(1550, -50, 50);
  forward(1000, -35);
  turn(1550, -50, 50);
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous pha

  //TODO: Selection Menu

  if (actS == "lower" && act1 == "tubes")
  {
  	lowerToTubes();

  	tubeMed();
  }

  if (actS == "lower" && act1 == "IR")
  {
  	lowerIR();
  }

  stopMotors();
}
