#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sensorSonic,    sensorSONAR)
#pragma config(Sensor, S4,     twistSonic,     sensorSONAR)
#pragma config(Motor,  motorC,          motorIR,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorR1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR2,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorL1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBlPickup, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBm,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorLft1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLft2,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

  string actS = "lower"; //Starting place
  string act1 = "IR"; //First action
  string act2 = "dropMed"; //Second action

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

/*
*
* HELPER TASKS
*
*/

//Travel set rotations

void forward(int dist, int power)
{
	nMotorEncoder[motorR2] = 0;
	nMotorEncoder[motorL2] = 0;

	while (abs(nMotorEncoder[motorR2]) <= abs(dist))
	{
		if (abs(nMotorEncoder[motorR2]) > abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
		else if (abs(nMotorEncoder[motorR2]) < abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
		else
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
	}
}

//Turn set rotations - 1800 = 45 degrees
void turn(int dist, int powerL, int powerR)
{
	if (powerL < powerR)
	{
		nMotorEncoder[motorR2] = 0;

		while (abs(nMotorEncoder[motorR2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
	else
	{
		nMotorEncoder[motorR2] = 0;

		while (abs(nMotorEncoder[motorR2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
}

//Travel set rotations
void stopMotors()
{
	motor[motorR1] = 0;
	motor[motorL1] = 0;
	motor[motorR2] = 0;
	motor[motorL2] = 0;
}

/*
*
* Core Code
*
*/

//Travel from the scoring zone to the tubes
void lowerToTubes()
{
  forward(2100, -70);
  turn(1400, 10, -60);
  forward(2000, -50);
  turn(1500, -60, 10);
  forward(3600, -40);
}
void kickstand()
{
	forward(500, 30);
  while(nMotorEncoder[motorC] < 90)
	{
		motor[motorC] = 30;
	}
	motor[motorC] = 0;

		motor[motorR1] = -30;
		motor[motorR2] = -30;
		motor[motorL1] = 30;
		motor[motorL2] = 30;
		Sleep(1200);

	stopMotors();
	while(nMotorEncoder[motorC] > 0)
	{
		motor[motorC] = -30;
	}
	motor[motorC] = 0;
	forward(1500, -30);
	motor[motorR1] = 25;
	motor[motorR2] = 25;
	motor[motorL1] = -25;
	motor[motorL2] = -25;
	Sleep(200);
	while(SensorValue[twistSonic] > 120 && SensorValue[sensorSonic] > 120)
	{
		motor[motorR1] = 23;
		motor[motorR2] = 23;
		motor[motorL1] = -23;
		motor[motorL2] = -23;
	}
	Sleep(100);
	stopMotors();
	forward(1000, -30);
  while(nMotorEncoder[motorC] < 90)
	{
		motor[motorC] = 30;
	}
	motor[motorC] = 0;


	motor[motorR1] = -90;
	motor[motorR2] = -90;
	motor[motorL1] = -90;
	motor[motorL2] = -90;
	Sleep(500);
	motor[motorR1] = 50;
	motor[motorR2] = 50;
	motor[motorL1] = 50;
	motor[motorL2] = 50;
	Sleep(2300);
	motor[motorR1] = 0;
	motor[motorR2] = 0;
	motor[motorL1] = 0;
	motor[motorL2] = 0;

}
//Score in medium tube
void dumpMed()
{
	bool runLift = true;
	servo[servo3] = 80;
	while(runLift == true)
	{
		motor[motorLft2] = 50;
	 	motor[motorLft1] = 50;
		if(nMotorEncoder[motorLft2] < -2400)
		{
			runLift = false;
		}
	}
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
	while(nMotorEncoder[motorBm] > -650)
	{
		motor[motorBm] = -30;
	}
	while(nMotorEncoder[motorBm] > -1000)
	{
		motor[motorBm] = -1;
	}
	motor[motorBm] = 10;
	Sleep(700);
	motor[motorBm] = 0;
	Sleep(300);
	servo[servo3] = 120;
	Sleep(1000);

	int LiftRunning = 1;

	while(nMotorEncoder[motorBm] < -650)
	{
		motor[motorBm] = 30;
	}
	while(nMotorEncoder[motorBm] < -300)
	{
		motor[motorBm] = 1;
	}
	motor[motorBm] = 80;
	Sleep(300);
	while(nMotorEncoder[motorBm] < -25)
	{
		motor[motorBm] = 7;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(LiftRunning == 1)
	{
		if(nMotorEncoder[motorLft2] > -720)
		{
			if(nMotorEncoder[motorLft2] < -100)
			{
				motor[motorLft2] = -20;
				motor[motorLft1] = -20;
			}
			else
			{
				motor[motorLft2] = 0;
				motor[motorLft1] = 0;
				LiftRunning = 0;
			}
		}
		else
		{
			motor[motorLft2] = -40;
			motor[motorLft1] = -40;
		}
	}
}


//Score in medium tube
void dumpCenter()
{
	bool runLift = true;
	servo[servo3] = 230;
	while(runLift == true)
	{
		motor[motorLft2] = 80;
	 	motor[motorLft1] = 80;
		if(nMotorEncoder[motorLft2] < -6150)
		{
			runLift = false;
		}
	}
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
	servo[servo3] = 80;
	while(nMotorEncoder[motorBm] > -650)
	{
		motor[motorBm] = -30;
	}

	while(nMotorEncoder[motorBm] > -800)
	{
		motor[motorBm] = -1;
	}
	motor[motorBm] = 10;
	Sleep(500);
	motor[motorBm] = 0;
	Sleep(300);
	Sleep(1000);
	motor[motorBm] = 20;
	Sleep(250);
	motor[motorBm] = -20;
	Sleep(250);
	motor[motorBm] = 20;
	Sleep(250);
	motor[motorBm] = -20;
	Sleep(250);
	servo[servo3] = 230;


	int LiftRunning = 1;

	while(nMotorEncoder[motorBm] < -650)
	{
		motor[motorBm] = 30;
	}
	while(nMotorEncoder[motorBm] < -300)
	{
		motor[motorBm] = 1;
	}
	motor[motorBm] = 0;
	Sleep(300);
	forward(30, 2600);
	stopMotors();
	while(nMotorEncoder[motorBm] < -25)
	{
		motor[motorBm] = 10;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(LiftRunning == 1)
	{
		if(nMotorEncoder[motorLft2] > -1720)
		{
			if(nMotorEncoder[motorLft2] < -1200)
			{
				motor[motorLft2] = -20;
				motor[motorLft1] = -20;
			}
			else
			{
				motor[motorLft2] = 0;
				motor[motorLft1] = 0;
				LiftRunning = 0;

			}
		}
		else
		{
			motor[motorLft2] = -40;
			motor[motorLft1] = -40;
		}
	}
}

void tubeMed()
{
  turn(1620, 50, -50);
  forward(1300, -50);
  stopMotors();
	dumpMed();
}

void lowerIR()
{
	nMotorEncoder[motorC] = 0;
	while(nMotorEncoder[motorC] < 90)
	{
		motor[motorC] = 30;
	}
	motor[motorC] = 0;
	int sonar = SensorValue[sensorSonic];
	int sonarTurn = SensorValue[twistSonic];

	if(sonar < 115)
	{
		while(SensorValue[sensorSonic] > 12)
		{
			motor[motorR1] = -30;
			motor[motorR2] = -30;
			motor[motorL1] = -30;
			motor[motorL2] = -30;
		}
		stopMotors();
		while(nMotorEncoder[motorIR] > 0)
		{
			motor[motorIR] = -20;
		}
		motor[motorIR] = 0;
		dumpCenter();

		kickstand();
		return;
	}

	forward(1600, -25);
	stopMotors();
	//stopMotors();
	while(nMotorEncoder[motorC] > 0)
	{
		motor[motorC] = -30;
	}
	motor[motorC] = 0;
	nMotorEncoder[motorIR] = 0;
	//Sleep(1000);
	sonar = SensorValue[sensorSonic];
	sonarTurn = SensorValue[twistSonic];
	//int ir1 = SensorValue[sensorIR];

	//while(nMotorEncoder[motorIR] > -48)
	//{
	//	motor[motorIR] = -10;
	//}

	//motor[motorIR] = 0;

	//int ir2 = SensorValue[sensorIR];

	//while(nMotorEncoder[motorIR] < 48)
	//{
	//	motor[motorIR] = 10;
	//}

	//motor[motorIR] = 0;

	//int ir3 = SensorValue[sensorIR];

	//while(nMotorEncoder[motorIR] < 100)
	//{
	//	motor[motorIR] = 10;
	//}

	//motor[motorIR] = 0;

	//int ir4 = SensorValue[sensorIR];

	//nxtDisplayTextLine(1, "%d", ir1);
	//nxtDisplayTextLine(2, "%d", ir2);
	//nxtDisplayTextLine(3, "%d", ir3);
	//nxtDisplayTextLine(4, "%d", ir4);
	//nxtDisplayTextLine(5, "%d", sonar);

	//while(nMotorEncoder[motorIR] > 0)
	//{
	//	motor[motorIR] = -10;
	//}

	motor[motorIR] = 0;
	if(sonar < 200 || sonarTurn < 150)
	{

		PlayTone(300, 300);
		forward(1000, -65);
	  motor[motorR1] = 35;
		motor[motorR2] = 35;
		motor[motorL1] = -35;
		motor[motorL2] = -35;
		Sleep(1000);
		motor[motorR1] = 0;
		motor[motorR2] = 0;
		motor[motorL1] = 0;
		motor[motorL2] = 0;
	  forward(2500, -35);
	  turn(1500, 50, -50);
	  forward(1300, -35);
		motor[motorR1] = -30;
		motor[motorR2] = -30;
		motor[motorL1] = 30;
		motor[motorL2] = 30;
		Sleep(1000);
		while(SensorValue[twistSonic] > 75) //TODO: replace with sonic
	  {
	  	motor[motorR1] = -20;
			motor[motorR2] = -20;
			motor[motorL1] = 20;
			motor[motorL2] = 20;
	  }


	  motor[motorR1] = -25;
		motor[motorR2] = -25;
		motor[motorL1] = -25;
		motor[motorL2] = -25;
		Sleep(400);
		motor[motorR1] = 0;
		motor[motorR2] = 0;
		motor[motorL1] = 0;
		motor[motorL2] = 0;
	  stopMotors();

	  dumpCenter();
	  while(nMotorEncoder[motorIR] > 0)
		{
			motor[motorIR] = -20;
		}
		kickstand();
	}
	else
	{


		forward(500, -65);
		motor[motorR1] = 25;
		motor[motorR2] = 25;
		motor[motorL1] = -25;
		motor[motorL2] = -25;
		Sleep(1000);
		motor[motorR1] = 0;
		motor[motorR2] = 0;
		motor[motorL1] = 0;
		motor[motorL2] = 0;
		forward(1250, -35);
		turn(1650, 50, -50);
		while(SensorValue[sensorSonic] > 45)
	  {
	  	motor[motorR1] = -20;
			motor[motorR2] = -20;
			motor[motorL1] = 20;
			motor[motorL2] = 20;


	  }
			motor[motorR1] = -30;
			motor[motorR2] = -30;
			motor[motorL1] = -30;
			motor[motorL2] = -30;
			Sleep(1500);

		stopMotors();
		dumpCenter();
		while(nMotorEncoder[motorIR] > 0)
		{
			motor[motorIR] = -20;
		}
		kickstand();
	}

}

task main()
{
  //initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous pha

  //TODO: Selection Menu
	initializeRobot();
	nMotorEncoder[motorBm] = 0;
	nMotorEncoder[motorLft2] = 0;

	waitForStart();
	servo[servo3] = 230;
	servo[servo4] = 240;
	servo[servo5] = 80;
	motor[motorLft2] = 50;
	motor[motorLft1] = 50;
	Sleep(500);
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
  lowerIR();
	stopMotors();

}
