#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sensorSonic,    sensorSONAR)
#pragma config(Sensor, S4,     sensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorC,          motorIR,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorR1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR2,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorL1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorBlPickup, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBm,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorLft1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLft2,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void forward(int dist, int power)
{
	nMotorEncoder[motorR2] = 0;
	nMotorEncoder[motorL2] = 0;

	while (abs(nMotorEncoder[motorR2]) <= abs(dist))
	{
		if (abs(nMotorEncoder[motorR2]) > abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
		else if (abs(nMotorEncoder[motorR2]) < abs(nMotorEncoder[motorL2]))
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
		else
		{
			motor[motorR1] = power;
			motor[motorL1] = power;
			motor[motorR2] = power;
			motor[motorL2] = power;
		}
	}
}

//Turn set rotations - 1800 = 45 degrees
void turn(int dist, int powerL, int powerR)
{
	if (powerL < powerR)
	{
		nMotorEncoder[motorL2] = 0;

		while (abs(nMotorEncoder[motorL2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
	else
	{
		nMotorEncoder[motorR2] = 0;

		while (abs(nMotorEncoder[motorR2]) <= abs(dist))
		{
			motor[motorR1] = powerR;
			motor[motorR2] = powerR;
			motor[motorL1] = powerL;
			motor[motorL2] = powerL;
		}
	}
}
void stopMotors()
{
	motor[motorR1] = 0;
	motor[motorL1] = 0;
	motor[motorR2] = 0;
	motor[motorL2] = 0;
}
task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.
  servo[servo3] = 80;
	servo[servo4] = 240;
	servo[servo5] = 80;
	nMotorEncoder[motorBm] = 0;
  nMotorEncoder[motorLft2] = 0;
  motor[motorLft2] = 50;
	motor[motorLft1] = 50;
	Sleep(500);
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
  nMotorEncoder[motorLft2] = 0;
	forward(1000, 30);

	servo[servo4] = 240;
	servo[servo5] = 80;
	forward(4000, 20);
	forward(2000, 30);
	forward(300, 30);
	motor[motorR1] = -50;
	motor[motorR2] = -50;
	motor[motorL1] = 50;
	motor[motorL2] = 50;
	Sleep(1400);
	motor[motorR1] = 0;
	motor[motorR2] = 0;
	motor[motorL1] = 0;
	motor[motorL2] = 0;
	while(SensorValue[sensorSonic] > 55) //TODO: replace with sonic
	  {
	  	motor[motorR1] = -25;
			motor[motorR2] = -25;
			motor[motorL1] = 25;
			motor[motorL2] = 25;
	  }
	stopMotors();

	Sleep(500);
	forward(1000, -25);
	servo[servo4] = 172;
	servo[servo5] = 150;
	forward(1250, -30);
	stopMotors();
	bool runLift = true;

	while(runLift == true)
	{
		motor[motorLft2] = 50;
		motor[motorLft1] = 50;
		if(nMotorEncoder[motorLft2] < -2200)
		{
			runLift = false;
		}
	}
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
	while(nMotorEncoder[motorBm] > -550)
	{
		motor[motorBm] = -40;
	}
	while(nMotorEncoder[motorBm] > -950)
	{
		motor[motorBm] = -1;
	}
	motor[motorBm] = 10;
	Sleep(700);
	motor[motorBm] = 0;
	motor[motorLft2] = 30;
	motor[motorLft1] = 30;
	Sleep(300);
	motor[motorLft2] = 0;
	motor[motorLft1] = 0;
	servo[servo3] = 240;
	Sleep(1000);
	servo[servo3] = 80;
	int LiftRunning = 1;

	while(nMotorEncoder[motorBm] < -650)
	{
		motor[motorBm] = 30;
	}
	while(nMotorEncoder[motorBm] < -300)
	{
		motor[motorBm] = 1;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(nMotorEncoder[motorBm] < -25)
	{
		motor[motorBm] = 10;
	}
	motor[motorBm] = 0;
	Sleep(300);
	while(LiftRunning == 1)
	{
		if(nMotorEncoder[motorLft2] > -720)
		{
			if(nMotorEncoder[motorLft2] < -200)
			{
				motor[motorLft2] = -20;
				motor[motorLft1] = -20;
			}
			else
			{
				motor[motorLft2] = 0;
				motor[motorLft1] = 0;
				LiftRunning = 0;

			}
		}
		else
		{
			motor[motorLft2] = -40;
			motor[motorLft1] = -40;
		}
	}
	motor[motorR1] = -50;
	motor[motorR2] = -50;
	motor[motorL1] = 50;
	motor[motorL2] = 50;
	Sleep(400);
	motor[motorR1] = 0;
	motor[motorR2] = 0;
	motor[motorL1] = 0;
	motor[motorL2] = 0;
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

}
